name: QuickNicks
version: ${project.version}
main: tk.nimari.QuickNicks
api-version: 1.14
authors: [Nimāri]
description: A plugin designed to make setting nicks quick and easy!
commands:
  nick:
    usage: /<command>
