name: QuickNicks
version: ${project.version}
main: jp.marisa.quicknicks.Main
api-version: 1.18.2
authors: [Marisa]
description: A plugin designed to make setting nicks quick and easy!
commands:
  nick:
    usage: /<command>
